home_work_2
KatteSmi/InternshipLANIT pull request #2
Opened 2021-04-21 18:47 UTC by KatteSmi

2021-04-26 18:38 UTC, Teraule commented
результаты компиляции в коммите не нужны, файлы *.class не прикладываем

2021-04-26 18:45 UTC, Teraule requested changes

2021-04-26 18:45 UTC, Teraule commented on Zoopark/src/main/java/Zoo.java
> +            ((Swim) animal).swim();
опасно. а что если не прокатит? лучше тогда делать ```List<Swim>```, тогда точно сработает без сюрпризов

2021-04-26 18:45 UTC, Teraule commented on Zoopark/src/main/java/animals/Animal.java
> +    protected void setSatiety(Food food) {
incSatiety?

2021-04-26 18:45 UTC, Teraule commented on Zoopark/src/main/java/animals/Carnivorous.java
> +}
проще так:
```java
    public boolean eat(Food food) {
        if !(food instanceof Meat) {
            System.out.println("Эта еда не подходит!");
            return false;
        }
        System.out.println("Хищник накормлен!");
        this.setSatiety(food);
        return true;
    }
```

2021-04-26 18:45 UTC, Teraule commented on Zoopark/src/main/java/animals/Herbivore.java
> +        return false;
аналогично хищнику

2021-04-27 10:19 UTC, KatteSmi commented on Zoopark/src/main/java/animals/Animal.java
> +    protected void setSatiety(Food food) {
исправила

2021-04-27 10:19 UTC, KatteSmi commented on Zoopark/src/main/java/animals/Carnivorous.java
> +}
исправила

2021-04-27 10:19 UTC, KatteSmi commented on Zoopark/src/main/java/animals/Herbivore.java
> +        return false;
исправила

2021-04-27 10:19 UTC, KatteSmi commented on Zoopark/src/main/java/Zoo.java
> +            ((Swim) animal).swim();
исправила

2021-05-05 06:46 UTC, merged